# Generated by Django 4.1.7 on 2023-03-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('auth_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('auth_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('box_num', models.PositiveSmallIntegerField()),
                ('box_size', models.PositiveSmallIntegerField()),
                ('location', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Box_Maint',
            fields=[
                ('box_maint_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('disc_date_time', models.DateTimeField(auto_now_add=True)),
                ('fix_date_time', models.DateField(auto_now=True, null=True)),
                ('fix_by', models.CharField(blank=True, max_length=5, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box_Status',
            fields=[
                ('status_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('log_by', models.CharField(max_length=5)),
                ('disc_date_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('comp_by', models.CharField(blank=True, max_length=5, null=True)),
                ('comp_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('build_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('build_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('num_floors', models.PositiveSmallIntegerField()),
                ('num_ext', models.PositiveSmallIntegerField()),
                ('num_boxes', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Type',
            fields=[
                ('emp_type_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('role_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ext_Maint',
            fields=[
                ('ext_maint_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fail_date_time', models.DateTimeField(auto_now_add=True)),
                ('replace_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('replace_by', models.CharField(blank=True, max_length=5, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ext_Status',
            fields=[
                ('status_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ext_Tag',
            fields=[
                ('tag_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('5', 'Small box'), ('10', 'Large box')], default=None, max_length=2)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ext_status')),
            ],
        ),
        migrations.CreateModel(
            name='Ext_Type',
            fields=[
                ('type_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('type_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Extinguisher',
            fields=[
                ('ext_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('floor', models.PositiveIntegerField()),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.box')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ext_tag')),
            ],
        ),
        migrations.CreateModel(
            name='Insp_Status',
            fields=[
                ('insp_status', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('stat_desc', models.CharField(choices=[('Pass', 'Extinguisher has 100% Pass'), ('Fail', 'Extinguisher did not 100% Pass')], default=None, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='W_Insp_Status',
            fields=[
                ('insp_s_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(choices=[('Ready', 'Extinguisher ready for deployment'), ('Needs Inspection', 'Extinguisher waiting for inspection'), ('Send to EOL', 'Extinguisher ready for decommission'), ('Decommissioned', 'Extinguisher was terminated')], default='Needs Inspection', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ware_Ops',
            fields=[
                ('w_ext_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('rec_by', models.CharField(max_length=10)),
                ('rec_date_time', models.DateTimeField(auto_now_add=True)),
                ('insp_s_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('insp_by', models.CharField(blank=True, max_length=5, null=True)),
                ('insp_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('ext_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extinguisher')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('emp_status', models.CharField(choices=[('Active', 'Still working'), ('Resigned', 'No longer working')], default='Active', max_length=50)),
                ('emp_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emp_type')),
            ],
        ),
        migrations.CreateModel(
            name='Ready_Ext',
            fields=[
                ('ready_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ready_date_time', models.DateTimeField(auto_now=True)),
                ('w_ext_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ware_ops')),
            ],
        ),
        migrations.CreateModel(
            name='Maint_Staff',
            fields=[
                ('maint_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('box_maint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.box_maint')),
                ('emp_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emp_type')),
                ('ext_maint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ext_maint')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150)),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auth')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff')),
            ],
        ),
        migrations.AddField(
            model_name='ext_tag',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ext_type'),
        ),
        migrations.AddField(
            model_name='ext_status',
            name='insp_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.insp_status'),
        ),
        migrations.AddField(
            model_name='ext_status',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
        ),
        migrations.CreateModel(
            name='EOL_Ext',
            fields=[
                ('eol_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('eol_date_time', models.DateTimeField(auto_now=True)),
                ('w_ext_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ware_ops')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklist_id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('list_item', models.CharField(max_length=150)),
                ('emp_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emp_type')),
            ],
        ),
        migrations.CreateModel(
            name='C_Log',
            fields=[
                ('c_log_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('t_changed', models.CharField(max_length=30)),
                ('i_changed', models.CharField(max_length=30)),
                ('change_date_time', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.login')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='build_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building'),
        ),
        migrations.AddField(
            model_name='box',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ext_status'),
        ),
    ]
