# Generated by Django 4.1.7 on 2023-04-04 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSizes',
            fields=[
                ('size_ID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('5', 'Small box'), ('10', 'Large box')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ext_Model',
            fields=[
                ('ext_model_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Floor_Plan',
            fields=[
                ('layout_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('floor', models.PositiveSmallIntegerField()),
                ('file_txt', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='box',
            name='location',
        ),
        migrations.RemoveField(
            model_name='extinguisher',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='box',
            name='x_axis',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='y_axis',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extinguisher',
            name='status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ext_status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extinguisher',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ext_type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ext_Tag',
        ),
        migrations.AddField(
            model_name='ext_model',
            name='box_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.box'),
        ),
        migrations.AddField(
            model_name='ext_model',
            name='ext_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extinguisher'),
        ),
        migrations.AddField(
            model_name='building',
            name='layout_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.floor_plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extinguisher',
            name='size_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.boxsizes'),
            preserve_default=False,
        ),
    ]
