# Generated by Django 4.1.7 on 2023-04-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_boxsizes_ext_model_floor_plan_remove_box_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
