# Generated by Django 4.1.7 on 2023-04-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_staff_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='x_axis',
        ),
        migrations.AlterField(
            model_name='box',
            name='box_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='box',
            name='y_axis',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='box_status',
            name='status_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boxsizes',
            name='size_ID',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='num_boxes',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='building',
            name='num_ext',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='building',
            name='num_floors',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='c_log',
            name='c_log_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='checklist_id',
            field=models.CharField(default=1, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eol_ext',
            name='eol_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ext_status',
            name='status_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extinguisher',
            name='floor',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='floor_plan',
            name='floor',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='insp_status',
            name='insp_status',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='w_insp_status',
            name='insp_s_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ware_ops',
            name='insp_s_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
