# Generated by Django 4.1.7 on 2023-04-14 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ext_Status',
            new_name='ExtStatus',
        ),
    ]
