# Generated by Django 4.1.7 on 2023-04-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_ext_status_extstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Box_Maint',
            new_name='BoxMaint',
        ),
        migrations.RenameModel(
            old_name='Box_Status',
            new_name='BoxStatus',
        ),
        migrations.RenameModel(
            old_name='C_Log',
            new_name='CLog',
        ),
        migrations.RenameModel(
            old_name='Emp_Type',
            new_name='EmpType',
        ),
        migrations.RenameModel(
            old_name='EOL_Ext',
            new_name='EOLExt',
        ),
        migrations.RenameModel(
            old_name='Ext_Maint',
            new_name='ExtMaint',
        ),
        migrations.RenameModel(
            old_name='Ext_Model',
            new_name='ExtModel',
        ),
        migrations.RenameModel(
            old_name='Ext_Type',
            new_name='ExtType',
        ),
        migrations.RenameModel(
            old_name='Floor_Plan',
            new_name='FloorPlan',
        ),
        migrations.RenameModel(
            old_name='Insp_Status',
            new_name='InspStatus',
        ),
        migrations.RenameModel(
            old_name='Maint_Staff',
            new_name='MaintStaff',
        ),
        migrations.RenameModel(
            old_name='Ready_Ext',
            new_name='ReadyExt',
        ),
        migrations.RenameModel(
            old_name='Ware_Ops',
            new_name='WareOps',
        ),
        migrations.RenameModel(
            old_name='W_Insp_Status',
            new_name='WInspStatus',
        ),
    ]
