# Generated by Django 4.1.7 on 2023-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_checklist_list_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='file_txt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
