# Generated by Django 4.1.7 on 2023-04-19 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_remove_maintstaff_staff_id_remove_staff_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clog',
            name='login_id',
        ),
        migrations.AddField(
            model_name='clog',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
