# Generated by Django 4.1.7 on 2023-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_login_auth_id_remove_login_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='file_txt',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
