# Generated by Django 4.1.7 on 2023-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_inspectorassignments_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectorassignments',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='inspectorassignments',
            name='box_id',
        ),
        migrations.AddField(
            model_name='inspectorassignments',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
