# Generated by Django 4.1.7 on 2023-05-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_inspectorassignments_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectorassignments',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
