# Generated by Django 4.1.7 on 2023-05-06 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_inspectorassignments_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extinguisher')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extstatus')),
            ],
        ),
    ]
