# Generated by Django 4.1.7 on 2023-05-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_techassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='techassignments',
            name='warehouse_status',
            field=models.CharField(choices=[('Pending', 'Has not been inspected yet'), ('Pass', 'Passed Warehouse inspection'), ('Fail', 'Send to End of Life')], default='Pending', max_length=50),
        ),
    ]
