# Generated by Django 4.1.7 on 2023-05-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_techassignments_warehouse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='techassignments',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
